on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to add links
    steps:
      - uses: actions/checkout@v2
      - name: Run link 
        uses: jrtolley/add-pr-link@v1
        env:
          NETLIFY_URL: http://www.test.com 
          PR_NUMBER: 435
          SHORTCUT_API_KEY: ${{ secrets.SHORTCUT_API_KEY }} 
